
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

minimumReleaseAgeExclude:
  - centoui-cli@1.11.1
  - centoui-nuxt@1.11.1
  - centoui@1.11.1
shellEmulator: true


trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - nanoid@3.3.14


