export default defineAppConfig({
  owner: {
    name: 'Favour Emeka',
    email: 'favorodera@gmail.com',
    contact: [
      { label: 'GitHub', icon: 'simple-icons:github', to: 'https://github.com/favorodera' },
      { label: 'X (Twitter)', icon: 'simple-icons:x', to: 'https://x.com/favorodera' },
      { label: 'LinkedIn', icon: 'simple-icons:linkedin', to: 'https://linkedin.com/in/favorodera' },
      { label: 'Facebook', icon: 'simple-icons:facebook', to: 'https://facebook.com/favorodera' },
    ],
  },

  ui: {
    prose: {
      h1: { slots: { base: 'text-2xl ' } },
      h2: { slots: { base: 'text-xl' } },
      h3: { slots: { base: 'text-lg' } },
      h4: { slots: { base: 'text-base' } },
      p: { base: 'dark:text-muted' },
      strong: { base: 'text-default' },
      figure: { base: 'rounded-lg' },
      ul: { base: 'dark:text-muted' },
      ol: { base: 'dark:text-muted' },
      figcaption: { base: 'm-0 py-1 text-center' },
      hr: { base: 'mx-auto my-8 max-w-1/2' },
      callout: { slots: { icon: 'size-5' } },
      a: { base: 'hover:border-secondary' },
    },
    colors: {
      neutral: 'neutral',
      secondary: 'teal',
    },
    icons: {
      light: 'ph:sun',
      dark: 'ph:moon',
      external: 'ph:arrow-up-right',
      loading: 'ph:circle-notch',
      arrowDown: 'ph:arrow-down',
      arrowLeft: 'ph:arrow-left',
      arrowRight: 'ph:arrow-right',
      arrowUp: 'ph:arrow-up',
      caution: 'ph:warning-circle',
      check: 'ph:check',
      chevronDoubleLeft: 'ph:caret-double-left',
      chevronDoubleRight: 'ph:caret-double-right',
      chevronDown: 'ph:caret-down',
      chevronLeft: 'ph:caret-left',
      chevronRight: 'ph:caret-right',
      chevronUp: 'ph:caret-up',
      close: 'ph:x',
      copy: 'ph:copy-simple',
      copyCheck: 'ph:check-square',
      ellipsis: 'ph:dots-three',
      error: 'ph:x-circle',
      eye: 'ph:eye',
      eyeOff: 'ph:eye-slash',
      file: 'ph:file',
      folder: 'ph:folder',
      folderOpen: 'ph:folder-open',
      hash: 'ph:hash',
      info: 'ph:info',
      menu: 'ph:list',
      minus: 'ph:minus',
      panelClose: 'ph:arrow-square-left',
      panelOpen: 'ph:arrow-square-right',
      plus: 'ph:plus',
      reload: 'ph:arrows-clockwise',
      search: 'ph:magnifying-glass',
      stop: 'ph:stop',
      success: 'ph:check-circle',
      system: 'ph:monitor',
      tip: 'ph:lightbulb',
      upload: 'ph:upload',
      warning: 'ph:warning',
    },
    pageHeader: { slots: { root: 'border-none', title: 'text-2xl sm:text-2xl', description: 'mt-5 text-base' } },
    formField: { slots: { label: 'font-medium' } },
    button: { slots: { base: 'cursor-pointer' } },
    checkbox: { slots: { root: 'cursor-pointer' } },
    dropdownMenu: { slots: { item: 'cursor-pointer' } },
    input: { slots: { root: 'w-full' } },
    inputMenu: { slots: { root: 'w-full' } },
    inputNumber: { slots: { root: 'w-full' } },
    textarea: { slots: { root: 'w-full', base: 'resize-none' } },
    tabs: { slots: { trigger: 'cursor-pointer' } },
    selectMenu: { slots: { base: 'cursor-pointer text-start w-full', item: 'cursor-pointer' } },
    select: { slots: { base: 'cursor-pointer text-start w-full', item: 'cursor-pointer' } },
    inputTags: { slots: { base: 'w-full' } },
    navigationMenu: { slots: { link: 'cursor-pointer' } },
    fileUpload: { slots: { base: 'cursor-pointer' } },
    toast: { slots: { root: 'bg-elevated ring-0' } },
    commandPalette: { slots: { item: 'cursor-pointer' } },
  },
})
