export default defineAppConfig({
  owner: {
    name: 'Favour Emeka',
    email: 'favorodera@gmail.com',
    contact: [
      { label: 'GitHub', icon: 'simple-icons:github', to: 'https://github.com/favorodera' },
      { label: 'X (Twitter)', icon: 'simple-icons:x', to: 'https://x.com/favorodera' },
      { label: 'LinkedIn', icon: 'simple-icons:linkedin', to: 'https://linkedin.com/in/favorodera' },
      { label: 'Facebook', icon: 'simple-icons:facebook', to: 'https://facebook.com/favorodera' },
    ],
  },

  ui: {
    prose: {
      h1: { slots: { base: 'text-xl mb-4' } },
      h2: { slots: { base: 'mb-2 text-lg' } },
      h3: { slots: { base: 'text-base' } },
      h4: { slots: { base: '' } },
      p: { base: 'my-4 dark:text-muted' },
      a: { base: 'border-default font-medium no-underline hover:border-accented dark:text-muted' },
      strong: { base: 'dark:text-default' },
      code: { base: 'text-sm' },
      pre: { slots: { base: 'text-default' } },
      ol: { base: 'dark:text-muted' },
      ul: { base: 'dark:text-muted' },
      table: { slots: { root: 'block overflow-x-scroll' } },
      img: { slots: { base: 'rounded-lg border border-default dark:border-muted' } },
      figure: { base: 'rounded-lg bg-elevated dark:bg-muted' },
      figcaption: { base: 'm-0 py-1 text-center' },
      video: { base: 'rounded-lg border border-default dark:border-muted' },
      hr: { base: 'mx-auto my-8 max-w-1/2 border-muted' },
    },

    colors: {
      primary: 'black',
      neutral: 'neutral',
    },
    icons: {
      light: 'ph:sun',
      dark: 'ph:moon',
      external: 'ph:arrow-up-right',
      loading: 'ph:circle-notch',
    },
    formField: { slots: { label: 'font-medium' } },
    button: { slots: { base: 'cursor-pointer' } },
    checkbox: { slots: { root: 'cursor-pointer' } },
    dropdownMenu: { slots: { item: 'cursor-pointer' } },
    input: { slots: { root: 'w-full' } },
    inputMenu: { slots: { root: 'w-full' } },
    inputNumber: { slots: { root: 'w-full' } },
    textarea: { slots: { root: 'w-full', base: 'resize-none' } },
    tabs: { slots: { trigger: 'cursor-pointer' } },
    selectMenu: { slots: { base: 'cursor-pointer text-start w-full', item: 'cursor-pointer' } },
    select: { slots: { base: 'cursor-pointer text-start w-full', item: 'cursor-pointer' } },
    inputTags: { slots: { base: 'w-full' } },
    navigationMenu: { slots: { link: 'cursor-pointer' } },
    fileUpload: { slots: { base: 'cursor-pointer' } },
    toast: { slots: { root: 'bg-elevated ring-0' } },
    commandPalette: { slots: { item: 'cursor-pointer' } },
  },
})
