name: CI

on: [push, pull_request]

permissions:
  statuses: write

jobs:
  ci:
    name: Lint, Typecheck & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.8

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Notify Vercel
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: CI Checks
